### ISSUE TITLE
I want to take over this package

### ISSUE THREAD

**Issue by apla** [joeferner/node-db-info#2]
Some modules have changed methods, like `mysql`, we have official `oracledb` driver, I've added support for `mssql` and so on. You can check current progress in my fork here: https://github.com/apla/node-db-info/

**Comment by joeferner** [comment]
Sounds good to me. Obviously I haven't touched this package in quite some time. I have given you collaborator access. I tried transferring ownership but since you have a fork with the same name in your account I couldn't do that. I also added apla to the npm owner list.

**Comment by apla** [comment]
Thank you!
